version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "19:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: redux
    versions:
    - 4.0.5
  - dependency-name: handlebars
    versions:
    - 4.7.6
